steps:
- name: golang:1.19
  dir: 'grpcgcp'
  entrypoint: go
  args: ['test', '-v', '-timeout', '600s']
- name: golang:1.19
  dir: 'grpcgcp'
  entrypoint: go
  args: ['test', '-v', '-timeout', '600s', 'github.com/GoogleCloudPlatform/grpc-gcp-go/grpcgcp/test_grpc']
- name: golang:1.19
  dir: 'grpcgcp_tests'
  env:
  - 'GCP_PROJECT_ID=grpc-gcp-testing'
  entrypoint: go
  args: ['test', '-v', '-timeout', '600s']
