// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.6
// source: grpc_gcp/testing/test.proto

package testing

import (
	messages "continuous_load_testing/proto/grpc/testing/messages"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_grpc_gcp_testing_test_proto protoreflect.FileDescriptor

const file_grpc_gcp_testing_test_proto_rawDesc = "" +
	"\n" +
	"\x1bgrpc_gcp/testing/test.proto\x12 grpc_gcp.continuous_load_testing\x1a\x1bgrpc/testing/messages.proto2k\n" +
	"\vTestService\x12\\\n" +
	"\x1bStreamedSequentialUnaryCall\x12\x1b.grpc.testing.SimpleRequest\x1a\x1c.grpc.testing.SimpleResponse(\x010\x01B0Z.continuous_load_testing/proto/grpc_gcp/testingb\x06proto3"

var file_grpc_gcp_testing_test_proto_goTypes = []any{
	(*messages.SimpleRequest)(nil),  // 0: grpc.testing.SimpleRequest
	(*messages.SimpleResponse)(nil), // 1: grpc.testing.SimpleResponse
}
var file_grpc_gcp_testing_test_proto_depIdxs = []int32{
	0, // 0: grpc_gcp.continuous_load_testing.TestService.StreamedSequentialUnaryCall:input_type -> grpc.testing.SimpleRequest
	1, // 1: grpc_gcp.continuous_load_testing.TestService.StreamedSequentialUnaryCall:output_type -> grpc.testing.SimpleResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_gcp_testing_test_proto_init() }
func file_grpc_gcp_testing_test_proto_init() {
	if File_grpc_gcp_testing_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_gcp_testing_test_proto_rawDesc), len(file_grpc_gcp_testing_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_gcp_testing_test_proto_goTypes,
		DependencyIndexes: file_grpc_gcp_testing_test_proto_depIdxs,
	}.Build()
	File_grpc_gcp_testing_test_proto = out.File
	file_grpc_gcp_testing_test_proto_goTypes = nil
	file_grpc_gcp_testing_test_proto_depIdxs = nil
}
