// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.6
// source: grpc_gcp/testing/test.proto

package testing

import (
	empty "continuous_load_testing/proto/grpc_gcp/testing/empty"
	messages "continuous_load_testing/proto/grpc_gcp/testing/messages"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_grpc_gcp_testing_test_proto protoreflect.FileDescriptor

const file_grpc_gcp_testing_test_proto_rawDesc = "" +
	"\n" +
	"\x1bgrpc_gcp/testing/test.proto\x12 grpc_gcp.continuous_load_testing\x1a\x1cgrpc_gcp/testing/empty.proto\x1a\x1fgrpc_gcp/testing/messages.proto2\x96\t\n" +
	"\vTestService\x12]\n" +
	"\tEmptyCall\x12'.grpc_gcp.continuous_load_testing.Empty\x1a'.grpc_gcp.continuous_load_testing.Empty\x12n\n" +
	"\tUnaryCall\x12/.grpc_gcp.continuous_load_testing.SimpleRequest\x1a0.grpc_gcp.continuous_load_testing.SimpleResponse\x12w\n" +
	"\x12CacheableUnaryCall\x12/.grpc_gcp.continuous_load_testing.SimpleRequest\x1a0.grpc_gcp.continuous_load_testing.SimpleResponse\x12\x94\x01\n" +
	"\x13StreamingOutputCall\x12<.grpc_gcp.continuous_load_testing.StreamingOutputCallRequest\x1a=.grpc_gcp.continuous_load_testing.StreamingOutputCallResponse0\x01\x12\x91\x01\n" +
	"\x12StreamingInputCall\x12;.grpc_gcp.continuous_load_testing.StreamingInputCallRequest\x1a<.grpc_gcp.continuous_load_testing.StreamingInputCallResponse(\x01\x12\x91\x01\n" +
	"\x0eFullDuplexCall\x12<.grpc_gcp.continuous_load_testing.StreamingOutputCallRequest\x1a=.grpc_gcp.continuous_load_testing.StreamingOutputCallResponse(\x010\x01\x12\x91\x01\n" +
	"\x0eHalfDuplexCall\x12<.grpc_gcp.continuous_load_testing.StreamingOutputCallRequest\x1a=.grpc_gcp.continuous_load_testing.StreamingOutputCallResponse(\x010\x01\x12e\n" +
	"\x11UnimplementedCall\x12'.grpc_gcp.continuous_load_testing.Empty\x1a'.grpc_gcp.continuous_load_testing.Empty\x12\x84\x01\n" +
	"\x1bStreamedSequentialUnaryCall\x12/.grpc_gcp.continuous_load_testing.SimpleRequest\x1a0.grpc_gcp.continuous_load_testing.SimpleResponse(\x010\x01B0Z.continuous_load_testing/proto/grpc_gcp/testingb\x06proto3"

var file_grpc_gcp_testing_test_proto_goTypes = []any{
	(*empty.Empty)(nil),                          // 0: grpc_gcp.continuous_load_testing.Empty
	(*messages.SimpleRequest)(nil),               // 1: grpc_gcp.continuous_load_testing.SimpleRequest
	(*messages.StreamingOutputCallRequest)(nil),  // 2: grpc_gcp.continuous_load_testing.StreamingOutputCallRequest
	(*messages.StreamingInputCallRequest)(nil),   // 3: grpc_gcp.continuous_load_testing.StreamingInputCallRequest
	(*messages.SimpleResponse)(nil),              // 4: grpc_gcp.continuous_load_testing.SimpleResponse
	(*messages.StreamingOutputCallResponse)(nil), // 5: grpc_gcp.continuous_load_testing.StreamingOutputCallResponse
	(*messages.StreamingInputCallResponse)(nil),  // 6: grpc_gcp.continuous_load_testing.StreamingInputCallResponse
}
var file_grpc_gcp_testing_test_proto_depIdxs = []int32{
	0, // 0: grpc_gcp.continuous_load_testing.TestService.EmptyCall:input_type -> grpc_gcp.continuous_load_testing.Empty
	1, // 1: grpc_gcp.continuous_load_testing.TestService.UnaryCall:input_type -> grpc_gcp.continuous_load_testing.SimpleRequest
	1, // 2: grpc_gcp.continuous_load_testing.TestService.CacheableUnaryCall:input_type -> grpc_gcp.continuous_load_testing.SimpleRequest
	2, // 3: grpc_gcp.continuous_load_testing.TestService.StreamingOutputCall:input_type -> grpc_gcp.continuous_load_testing.StreamingOutputCallRequest
	3, // 4: grpc_gcp.continuous_load_testing.TestService.StreamingInputCall:input_type -> grpc_gcp.continuous_load_testing.StreamingInputCallRequest
	2, // 5: grpc_gcp.continuous_load_testing.TestService.FullDuplexCall:input_type -> grpc_gcp.continuous_load_testing.StreamingOutputCallRequest
	2, // 6: grpc_gcp.continuous_load_testing.TestService.HalfDuplexCall:input_type -> grpc_gcp.continuous_load_testing.StreamingOutputCallRequest
	0, // 7: grpc_gcp.continuous_load_testing.TestService.UnimplementedCall:input_type -> grpc_gcp.continuous_load_testing.Empty
	1, // 8: grpc_gcp.continuous_load_testing.TestService.StreamedSequentialUnaryCall:input_type -> grpc_gcp.continuous_load_testing.SimpleRequest
	0, // 9: grpc_gcp.continuous_load_testing.TestService.EmptyCall:output_type -> grpc_gcp.continuous_load_testing.Empty
	4, // 10: grpc_gcp.continuous_load_testing.TestService.UnaryCall:output_type -> grpc_gcp.continuous_load_testing.SimpleResponse
	4, // 11: grpc_gcp.continuous_load_testing.TestService.CacheableUnaryCall:output_type -> grpc_gcp.continuous_load_testing.SimpleResponse
	5, // 12: grpc_gcp.continuous_load_testing.TestService.StreamingOutputCall:output_type -> grpc_gcp.continuous_load_testing.StreamingOutputCallResponse
	6, // 13: grpc_gcp.continuous_load_testing.TestService.StreamingInputCall:output_type -> grpc_gcp.continuous_load_testing.StreamingInputCallResponse
	5, // 14: grpc_gcp.continuous_load_testing.TestService.FullDuplexCall:output_type -> grpc_gcp.continuous_load_testing.StreamingOutputCallResponse
	5, // 15: grpc_gcp.continuous_load_testing.TestService.HalfDuplexCall:output_type -> grpc_gcp.continuous_load_testing.StreamingOutputCallResponse
	0, // 16: grpc_gcp.continuous_load_testing.TestService.UnimplementedCall:output_type -> grpc_gcp.continuous_load_testing.Empty
	4, // 17: grpc_gcp.continuous_load_testing.TestService.StreamedSequentialUnaryCall:output_type -> grpc_gcp.continuous_load_testing.SimpleResponse
	9, // [9:18] is the sub-list for method output_type
	0, // [0:9] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_gcp_testing_test_proto_init() }
func file_grpc_gcp_testing_test_proto_init() {
	if File_grpc_gcp_testing_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_gcp_testing_test_proto_rawDesc), len(file_grpc_gcp_testing_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_gcp_testing_test_proto_goTypes,
		DependencyIndexes: file_grpc_gcp_testing_test_proto_depIdxs,
	}.Build()
	File_grpc_gcp_testing_test_proto = out.File
	file_grpc_gcp_testing_test_proto_goTypes = nil
	file_grpc_gcp_testing_test_proto_depIdxs = nil
}
