apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client-go-manual-cloudpath
  name: client-go-manual-cloudpath
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-go-manual-cloudpath
  template:
    metadata:
      labels:
        app: client-go-manual-cloudpath
    spec:
      containers:
      - image: "us-docker.pkg.dev/directpathgrpctesting-client/directpathgrpctesting-client/directpathgrpctesting-client-go-manual"
        imagePullPolicy: Always
        name: client-go-manual
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONTAINER_NAME
          value: client-go-manual-cloudpath
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: k8s.pod.name=$(POD_NAME),k8s.namespace.name=$(NAMESPACE_NAME),k8s.container.name=$(CONTAINER_NAME)
        - name: GOOGLE_CLOUD_DISABLE_DIRECT_PATH
          value: "true"
        resources:
          requests:
            cpu: "2"
            memory: "256Mi"
          limits:
            cpu: "2"
            memory: "1024Mi"
